### ISSUE TITLE
At least one of the NBA percentages are resulting in division by zero

### ISSUE THREAD

**Issue by morelandjs** [roclark/sportsipy#575]
When using the NBA module, at least one extended dataframe errors out due to division by zero. If the denominator of a percentage is zero, I would just return np.nan.

Here's the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 856, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/executors.py", line 298, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "deploy.py", line 60, in get_season_team
    df = Schedule(team, season).dataframe_extended
  File "/usr/local/lib/python3.8/site-packages/sportsipy/nba/schedule.py", line 486, in dataframe_extended
    df = game.dataframe_extended
  File "/usr/local/lib/python3.8/site-packages/sportsipy/nba/schedule.py", line 164, in dataframe_extended
    return self.boxscore.dataframe
  File "/usr/local/lib/python3.8/site-packages/sportsipy/nba/boxscore.py", line 778, in dataframe
    self.home_two_point_field_goal_percentage,
  File "/usr/local/lib/python3.8/site-packages/sportsipy/decorators.py", line 27, in wrapper
    value = func(*args)
  File "/usr/local/lib/python3.8/site-packages/sportsipy/nba/boxscore.py", line 1327, in home_two_point_field_goal_percentage
    result = float(self.home_two_point_field_goals) / \
ZeroDivisionError: float division by zero
```

**Comment by morelandjs** [comment]
You might consider using np.true_divide.
